// All peptides from thepeptidepedia.com — auto-synced
export const PEPTIDE_NAMES: string[] = [
  "BPC-157",
  "TB-500",
  "GHK-Cu",
  "Semaglutide",
  "Tirzepatide",
  "Retatrutide",
  "Sermorelin",
  "CJC-1295",
  "Ipamorelin",
  "PT-141 (Bremelanotide)",
  "NAD+",
  "MOTS-c",
  "Tesamorelin",
  "AOD-9604",
  "Epitalon",
  "Selank",
  "Semax",
  "Melanotan II",
  "Thymosin Alpha-1",
  "Kisspeptin",
  "LL-37",
  "DSIP",
  "KPV",
  "5-Amino-1MQ",
  "Melanotan I",
  "Oxytocin",
  "SS-31",
  "MGF",
  "CJC-1295 + Ipamorelin",
  "Tesamorelin + Ipamorelin",
  "Wolverine (BPC-157 + TB-500)",
  "Wolverine+ (BPC-157 + TB-500 + MGF)",
  "Glow (GHK-Cu + TB-500 + BPC-157)",
  "Glow+ (GHK-Cu + TB-500 + BPC-157 + KPV)",
  "Selank + Semax",
]
