// AUTO-GENERATED from thepeptidepedia.com — do not edit by hand
export const PEPTIDES = [
  {
    slug: "bpc-157",
    name: "BPC-157",
    aliases: ["Body Protection Compound 157", "PL 14736"],
    evidence: "Community consensus",
    evidenceTag: "community",
    reviewerNote: "No published human RCT data. Regimens are derived from community use reports and compounding pharmacy documentation. Treat all values as experimental.",
    contraindications: ["Known malignancy (theoretical angiogenesis concern)", "Active infection at injection site", "Pregnancy / breastfeeding \u2014 no safety data", "Competitive athletes \u2014 WADA prohibited substance (S0)"],
    routes: "Subcutaneous",
    commonVialMg: [5, 10],
    recommendedReconstitutionMl: [1, 2],
    reconstitutionNote: "Add bacteriostatic water slowly to the vial. Swirl gently — do not shake. The lyophilized powder should dissolve fully within ~60 seconds.",
    storageNote: "Store lyophilized vial refrigerated (2–8 °C). Reconstituted solution stable 30 days refrigerated. Do not freeze reconstituted peptide.",
    syringeNote: "Insulin syringe (U-100, 29–31 gauge, 1/2 inch) is standard. For doses requiring < 0.05 mL, consider adjusting reconstitution volume or use a micro-syringe.",
    lastReviewed: "2025-01-01",
    regimens: [
      {
        label: "Starter (conservative)",
        dosePerInjection_mg: 0.25,
        frequencyPerWeek: 5,
        route: "Subcutaneous",
        timingNote: "Any time — morning preferred on empty stomach",
        maxDurationDays: 84,
        evidenceTag: "Community consensus",
        warnings: ["No human clinical trial data", "WADA prohibited substance \u2014 do not use if subject to drug testing", "Not FDA approved for any use"],
        references: ["https://pubmed.ncbi.nlm.nih.gov/21443487/"],
      },
      {
        label: "Typical (community standard)",
        dosePerInjection_mg: 0.5,
        frequencyPerWeek: 5,
        route: "Subcutaneous",
        timingNote: "Morning or pre-sleep, consistent timing preferred",
        maxDurationDays: 84,
        evidenceTag: "Community consensus",
        warnings: ["No human clinical trial data", "WADA prohibited substance", "Not FDA approved"],
        references: ["https://pubmed.ncbi.nlm.nih.gov/25080996/"],
      },
      {
        label: "High-end (research protocols)",
        dosePerInjection_mg: 1,
        frequencyPerWeek: 7,
        route: "Subcutaneous",
        timingNote: "Split AM/PM if using twice daily",
        maxDurationDays: 56,
        evidenceTag: "Community consensus",
        warnings: ["No safety ceiling established in humans", "WADA prohibited substance", "Not FDA approved", "Exceeds typical community use \u2014 extra caution advised"],
      },
    ],
  },
  {
    slug: "cjc-1295",
    name: "CJC-1295",
    aliases: ["DAC:GRF", "CJC1295", "Drug Affinity Complex GRF"],
    evidence: "Human observational",
    evidenceTag: "observational",
    reviewerNote: "Modified GHRH analogue with extended half-life due to DAC. Some published human pharmacokinetic data; not FDA approved. Often used in combination with ipamorelin.",
    contraindications: ["Active malignancy", "Pregnancy / breastfeeding", "Acromegaly or excess GH state"],
    routes: "Subcutaneous",
    commonVialMg: [2, 5],
    recommendedReconstitutionMl: [1, 2],
    reconstitutionNote: "Add bacteriostatic water. Swirl gently. Allow 2–3 minutes to dissolve fully.",
    storageNote: "Lyophilized: refrigerate. Reconstituted: 30 days refrigerated. More stable than most peptides due to DAC modification.",
    syringeNote: "Insulin syringe (U-100). Less frequent dosing than ipamorelin — weekly injections common.",
    lastReviewed: "2025-01-01",
    regimens: [
      {
        label: "Weekly (1 mg/week)",
        dosePerInjection_mg: 1,
        frequencyPerWeek: 1,
        route: "Subcutaneous",
        timingNote: "Pre-sleep, consistent day of week",
        maxDurationDays: 90,
        evidenceTag: "Human observational",
        warnings: ["Not FDA approved", "GH-related effects possible (water retention, insulin sensitivity changes)", "DAC modification gives multi-day half-life \u2014 allow full washout before stacking"],
        references: ["https://pubmed.ncbi.nlm.nih.gov/16822850/"],
      },
      {
        label: "Twice weekly (1 mg × 2/week)",
        dosePerInjection_mg: 1,
        frequencyPerWeek: 2,
        route: "Subcutaneous",
        timingNote: "Pre-sleep, evenly spaced (e.g. Mon/Thu)",
        maxDurationDays: 90,
        evidenceTag: "Human observational",
        warnings: ["Not FDA approved", "Monitor IGF-1 if available", "Avoid stacking with other GHRH analogues"],
        references: ["https://pubmed.ncbi.nlm.nih.gov/16822850/"],
      },
    ],
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    aliases: ["Copper peptide GHK-Cu", "Glycyl-L-histidyl-L-lysine copper"],
    evidence: "Community consensus",
    evidenceTag: "community",
    reviewerNote: "Widely used topically (cosmetics); injectable use is off-label and based on community protocols. Limited human injectable evidence.",
    contraindications: ["Known copper hypersensitivity", "Wilson's disease or other copper metabolism disorders", "Pregnancy / breastfeeding \u2014 no safety data for injectable use"],
    routes: "Topical, Subcutaneous",
    commonVialMg: [50, 100, 200],
    recommendedReconstitutionMl: [1, 2, 5],
    reconstitutionNote: "Add bacteriostatic water slowly. GHK-Cu dissolves readily due to its small size. Solution will appear faintly blue/green — this is normal (copper complex).",
    storageNote: "Refrigerate reconstituted solution. Use within 30 days. Protect from light.",
    syringeNote: "For topical: no syringe needed. For SC injection (off-label): insulin syringe (U-100, 31-gauge). Topical application is the more common and better-studied route.",
    lastReviewed: "2025-01-01",
    regimens: [
      {
        label: "Topical (cosmetic use)",
        dosePerInjection_mg: 0,
        frequencyPerWeek: 7,
        route: "Topical",
        timingNote: "Apply to skin 1–2× daily",
        maxDurationDays: "$undefined",
        evidenceTag: "Human observational",
        warnings: ["Topical is the well-studied route \u2014 injectable is off-label", "Patch test before full application"],
        references: ["https://pubmed.ncbi.nlm.nih.gov/25809842/"],
      },
      {
        label: "Injectable — low dose",
        dosePerInjection_mg: 1,
        frequencyPerWeek: 5,
        route: "Subcutaneous",
        timingNote: "Pre-sleep preferred; avoid IM in sensitive areas",
        maxDurationDays: 60,
        evidenceTag: "Community consensus",
        warnings: ["No published human injectable RCT data", "Copper accumulation risk with prolonged use \u2014 no established ceiling", "Not FDA approved for injection"],
      },
      {
        label: "Injectable — higher dose",
        dosePerInjection_mg: 2,
        frequencyPerWeek: 5,
        route: "Subcutaneous",
        timingNote: "Pre-sleep",
        maxDurationDays: 30,
        evidenceTag: "Community consensus",
        warnings: ["No human safety data at this dose", "Copper accumulation risk", "Not FDA approved"],
      },
    ],
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    aliases: ["IPA", "NNC 26-0161"],
    evidence: "Community consensus",
    evidenceTag: "community",
    reviewerNote: "Growth hormone secretagogue. Limited human clinical data; primarily compounding pharmacy and community use for GH pulse stimulation. Not FDA approved.",
    contraindications: ["Active malignancy (GH stimulation could be contraindicated)", "Pregnancy / breastfeeding", "Hypothyroidism (untreated) \u2014 may blunt response", "Insulin resistance / poorly controlled diabetes"],
    routes: "Subcutaneous",
    commonVialMg: [2, 5, 10],
    recommendedReconstitutionMl: [1, 2],
    reconstitutionNote: "Add bacteriostatic water slowly. Swirl gently. Clear solution expected.",
    storageNote: "Lyophilized: refrigerate 2–8 °C. Reconstituted: use within 28 days refrigerated.",
    syringeNote: "Insulin syringe (U-100, 31-gauge). Common injection sites: abdomen.",
    lastReviewed: "2025-01-01",
    regimens: [
      {
        label: "Starter (100 mcg/day)",
        dosePerInjection_mg: 0.1,
        frequencyPerWeek: 7,
        route: "Subcutaneous",
        timingNote: "Pre-sleep on empty stomach (2h post last meal). GH pulse highest during slow-wave sleep.",
        maxDurationDays: 90,
        evidenceTag: "Community consensus",
        warnings: ["Not FDA approved", "May increase appetite", "Monitor IGF-1 levels if available", "Avoid in active cancer"],
      },
      {
        label: "Typical (200–300 mcg/injection, 1–2× daily)",
        dosePerInjection_mg: 0.2,
        frequencyPerWeek: 14,
        route: "Subcutaneous",
        timingNote: "AM fasted + pre-sleep. Both injections on empty stomach.",
        maxDurationDays: 90,
        evidenceTag: "Community consensus",
        warnings: ["Not FDA approved", "GH stimulation \u2014 potential insulin resistance with chronic use", "Titrate slowly"],
      },
      {
        label: "High-end (300 mcg × 3× daily)",
        dosePerInjection_mg: 0.3,
        frequencyPerWeek: 21,
        route: "Subcutaneous",
        timingNote: "AM / midday / pre-sleep, all fasted states",
        maxDurationDays: 60,
        evidenceTag: "Community consensus",
        warnings: ["No established safety ceiling in humans", "GH-related side effects: water retention, joint pain, carpal tunnel", "Not FDA approved"],
      },
    ],
  },
  {
    slug: "nad-plus",
    name: "NAD+",
    aliases: ["Nicotinamide adenine dinucleotide", "NAD", "NMN precursor"],
    evidence: "Human observational",
    evidenceTag: "observational",
    reviewerNote: "IV NAD+ administration studied in small human trials for addiction, aging, and fatigue. IV use is off-label; oral supplements widely used. Route significantly changes bioavailability.",
    contraindications: ["Active malignancy (theoretical \u2014 NAD+ fuels cell division)", "Pregnancy / breastfeeding \u2014 no safety data for IV use"],
    routes: "Intramuscular",
    commonVialMg: [100, 250, 500, 750],
    recommendedReconstitutionMl: [5, 10, 20],
    reconstitutionNote: "For IV use: typically diluted in 250–500 mL normal saline or D5W by a licensed provider. For IV push/bolus: reconstitute in 5–20 mL sterile saline. Infuse slowly to reduce flushing.",
    storageNote: "Lyophilized powder: room temperature or refrigerate. Once reconstituted: use within 24 hours. Light-sensitive — protect from UV.",
    syringeNote: "IV infusion: IV drip set (18–20 gauge catheter). Slow infusion over 1–4 hours minimizes flushing and chest tightness. Oral supplements: no syringe needed.",
    lastReviewed: "2025-01-01",
    regimens: [
      {
        label: "IV — low dose (250 mg)",
        dosePerInjection_mg: 250,
        frequencyPerWeek: 1,
        route: "Intramuscular",
        timingNote: "Morning infusion, 2–3 hours duration. Administered by licensed provider.",
        maxDurationDays: 30,
        evidenceTag: "Human observational",
        warnings: ["IV use requires clinical setting and licensed provider", "Flushing, chest tightness, headache at infusion \u2014 slow rate mitigates", "Not FDA approved as drug product for IV use"],
        references: ["https://pubmed.ncbi.nlm.nih.gov/29727620/"],
      },
      {
        label: "IV — standard (500 mg)",
        dosePerInjection_mg: 500,
        frequencyPerWeek: 2,
        route: "Intramuscular",
        timingNote: "Infuse over 2–4 hours; 2–3× per week during loading period",
        maxDurationDays: 30,
        evidenceTag: "Human observational",
        warnings: ["Must be administered by licensed provider", "Higher rate of side effects at 500 mg vs 250 mg", "Pre-medicate with saline if prone to flushing"],
      },
    ],
  },
  {
    slug: "pt-141",
    name: "PT-141 (Bremelanotide)",
    aliases: ["Bremelanotide", "Vyleesi"],
    evidence: "Clinical / FDA-approved",
    evidenceTag: "clinical",
    reviewerNote: "FDA-approved (Vyleesi 1.75 mg SC) for hypoactive sexual desire disorder (HSDD) in premenopausal women. Off-label use in men is community-documented.",
    contraindications: ["Cardiovascular disease \u2014 transient BP increase observed", "Concurrent use of naltrexone or other opioid antagonists (may reduce effect)", "Uncontrolled hypertension", "Pregnancy / breastfeeding"],
    routes: "Subcutaneous",
    commonVialMg: [1.75, 2, 10],
    recommendedReconstitutionMl: [1],
    reconstitutionNote: "Vyleesi comes in a single-use prefilled autoinjector. For compounded vials: add 1 mL bacteriostatic water, swirl gently.",
    storageNote: "Refrigerate at 2–8 °C. Vyleesi autoinjector may be stored at room temperature ≤30 °C for up to 30 days.",
    syringeNote: "Vyleesi uses a prefilled autoinjector. For compounded: insulin syringe (U-100). Standard injection site: abdomen or thigh.",
    lastReviewed: "2024-06-01",
    regimens: [
      {
        label: "FDA-approved dose (Vyleesi — women HSDD)",
        dosePerInjection_mg: 1.75,
        frequencyPerWeek: 2,
        route: "Subcutaneous",
        timingNote: "45 minutes before anticipated sexual activity; max 1× per 24h",
        maxDurationDays: "$undefined",
        evidenceTag: "Clinical / FDA-approved",
        warnings: ["Transient increase in blood pressure (systolic +6 mmHg on average)", "Nausea (~40% of patients) \u2014 consider antiemetic", "Hyperpigmentation with chronic use", "Avoid if cardiovascular disease present"],
        references: ["https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/210557s000lbl.pdf"],
      },
      {
        label: "Community starting dose (men — off-label)",
        dosePerInjection_mg: 0.5,
        frequencyPerWeek: 2,
        route: "Subcutaneous",
        timingNote: "45–60 minutes before activity",
        maxDurationDays: 30,
        evidenceTag: "Community consensus",
        warnings: ["Off-label use \u2014 no FDA approval for men", "Monitor blood pressure post-dose", "Nausea is common, especially at first use"],
      },
      {
        label: "Community typical dose (men — off-label)",
        dosePerInjection_mg: 1,
        frequencyPerWeek: 2,
        route: "Subcutaneous",
        timingNote: "45–60 minutes before activity",
        maxDurationDays: "$undefined",
        evidenceTag: "Community consensus",
        warnings: ["Off-label use in men", "Do not exceed 2 mg per dose (community consensus ceiling)", "Monitor BP; avoid in cardiovascular disease"],
      },
    ],
  },
  {
    slug: "selank",
    name: "Selank",
    aliases: ["TP-7", "Selank anxiolytic"],
    evidence: "Human observational",
    evidenceTag: "observational",
    reviewerNote: "Russian nootropic peptide with some human trial data (primarily Russian literature). Used intranasally. Not FDA approved; limited Western clinical data.",
    contraindications: ["Pregnancy / breastfeeding", "Concurrent use of benzodiazepines or anxiolytics without physician guidance"],
    routes: "Intranasal",
    commonVialMg: [5, 10],
    recommendedReconstitutionMl: [1, 2],
    reconstitutionNote: "Add bacteriostatic saline (not BAC water — nasal formulations use saline). For nasal spray: 300 mcg/mL is standard concentration. Use a nasal spray bottle.",
    storageNote: "Refrigerate at 2–8 °C. Use reconstituted solution within 14 days.",
    syringeNote: "Nasal spray bottle is the standard delivery device. Insulin syringe not required for intranasal route.",
    lastReviewed: "2025-01-01",
    regimens: [
      {
        label: "Intranasal — low (250 mcg/day)",
        dosePerInjection_mg: 0.25,
        frequencyPerWeek: 7,
        route: "Intranasal",
        timingNote: "Morning dose, 2 sprays per nostril",
        maxDurationDays: 14,
        evidenceTag: "Human observational",
        warnings: ["Not FDA approved", "Primarily studied in Russian literature \u2014 independent replication limited", "Monitor for sedation or mood changes"],
        references: ["https://pubmed.ncbi.nlm.nih.gov/18041290/"],
      },
      {
        label: "Intranasal — typical (500–750 mcg/day)",
        dosePerInjection_mg: 0.5,
        frequencyPerWeek: 7,
        route: "Intranasal",
        timingNote: "AM and midday, split dosing",
        maxDurationDays: 14,
        evidenceTag: "Human observational",
        warnings: ["Not FDA approved", "Avoid prolonged use without physician guidance"],
      },
    ],
  },
  {
    slug: "semaglutide",
    name: "Semaglutide",
    aliases: ["Ozempic", "Wegovy", "Rybelsus"],
    evidence: "Clinical / FDA-approved",
    evidenceTag: "clinical",
    reviewerNote: "FDA-approved for T2DM (Ozempic) and chronic weight management (Wegovy). Regimens based on FDA prescribing information. Compounded semaglutide is a separate, evolving regulatory topic.",
    contraindications: ["Personal or family history of medullary thyroid carcinoma", "Multiple endocrine neoplasia type 2 (MEN 2)", "Known hypersensitivity to semaglutide", "Pregnancy \u2014 use effective contraception; discontinue if pregnancy occurs", "Concurrent use of other GLP-1 receptor agonists"],
    routes: "Subcutaneous",
    commonVialMg: [1, 2, 5],
    recommendedReconstitutionMl: [1, 2],
    reconstitutionNote: "Commercial pens (Ozempic/Wegovy) come pre-filled — no reconstitution needed. For compounded vials: add bacteriostatic water slowly. Gently swirl to mix. Do NOT shake.",
    storageNote: "Unopened: refrigerate at 2–8 °C. In-use (pen/vial): may store at room temperature up to 30 °C for up to 56 days. Do not freeze.",
    syringeNote: "Commercial formulation uses dedicated Ozempic/Wegovy pen needles. For compounded vials: insulin syringe (U-100) is standard.",
    lastReviewed: "2024-12-01",
    regimens: [
      {
        label: "Initiation (Week 1–4)",
        dosePerInjection_mg: 0.25,
        frequencyPerWeek: 1,
        route: "Subcutaneous",
        timingNote: "Once weekly, any time of day, with or without food",
        maxDurationDays: 28,
        evidenceTag: "Clinical / FDA-approved",
        warnings: ["GI side effects (nausea, vomiting, diarrhea) most common at initiation", "Monitor for signs of pancreatitis", "Thyroid C-cell tumor risk \u2014 see Black Box Warning in prescribing info"],
        references: ["https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/213051s000lbl.pdf", "https://pubmed.ncbi.nlm.nih.gov/34170647/"],
      },
      {
        label: "Maintenance (Week 5–16)",
        dosePerInjection_mg: 0.5,
        frequencyPerWeek: 1,
        route: "Subcutaneous",
        timingNote: "Once weekly, consistent day of week recommended",
        maxDurationDays: "$undefined",
        evidenceTag: "Clinical / FDA-approved",
        warnings: ["Do not exceed 2 mg/week without physician oversight", "Monitor HbA1c and renal function", "Drug interactions: oral medications may have altered absorption due to delayed gastric emptying"],
        references: ["https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/213051s000lbl.pdf"],
        titrationSteps: [{"week": 5, "dosePerInjection_mg": 0.5, "note": "Increase from 0.25 mg if tolerated"}, {"week": 17, "dosePerInjection_mg": 1, "note": "Further escalation per physician guidance"}],
      },
      {
        label: "High-dose (up to 2 mg/week)",
        dosePerInjection_mg: 2,
        frequencyPerWeek: 1,
        route: "Subcutaneous",
        timingNote: "Once weekly",
        maxDurationDays: "$undefined",
        evidenceTag: "Clinical / FDA-approved",
        warnings: ["2 mg is the maximum approved weekly dose", "GI side effects more common at higher doses", "Requires physician supervision"],
        references: ["https://pubmed.ncbi.nlm.nih.gov/34170647/"],
      },
    ],
  },
  {
    slug: "tb-500",
    name: "TB-500",
    aliases: ["Thymosin Beta-4", "T\u03b24"],
    evidence: "Community consensus",
    evidenceTag: "community",
    reviewerNote: "Synthetic analogue of naturally occurring thymosin beta-4. Limited human trial data; primarily used in community injury-recovery protocols.",
    contraindications: ["Known malignancy (promotes angiogenesis/migration)", "Pregnancy / breastfeeding", "Active infection", "Competitive athletes \u2014 WADA prohibited (S0)"],
    routes: "Subcutaneous",
    commonVialMg: [5, 10],
    recommendedReconstitutionMl: [1, 2],
    reconstitutionNote: "Add bacteriostatic water slowly. Swirl gently. Clear to slightly cloudy solution expected.",
    storageNote: "Lyophilized: refrigerate. Reconstituted: use within 30 days refrigerated.",
    syringeNote: "Insulin syringe (U-100). Both SC and IM injection reported; SC most common.",
    lastReviewed: "2025-01-01",
    regimens: [
      {
        label: "Loading phase (injury recovery)",
        dosePerInjection_mg: 2.5,
        frequencyPerWeek: 2,
        route: "Subcutaneous",
        timingNote: "Any time; consistent schedule preferred",
        maxDurationDays: 42,
        evidenceTag: "Community consensus",
        warnings: ["No published human RCT data", "WADA prohibited", "Not FDA approved", "Malignancy contraindication \u2014 angiogenic mechanism"],
      },
      {
        label: "Maintenance (post-loading)",
        dosePerInjection_mg: 2.5,
        frequencyPerWeek: 1,
        route: "Subcutaneous",
        timingNote: "Once weekly, any time",
        maxDurationDays: 60,
        evidenceTag: "Community consensus",
        warnings: ["No human safety data", "WADA prohibited", "Not FDA approved"],
      },
    ],
  },
  {
    slug: "tirzepatide",
    name: "Tirzepatide",
    aliases: ["Mounjaro", "Zepbound"],
    evidence: "Clinical / FDA-approved",
    evidenceTag: "clinical",
    reviewerNote: "FDA-approved for T2DM (Mounjaro) and chronic weight management (Zepbound). Regimens from FDA prescribing information.",
    contraindications: ["Personal or family history of medullary thyroid carcinoma", "Multiple endocrine neoplasia type 2 (MEN 2)", "Known hypersensitivity to tirzepatide", "Pregnancy \u2014 discontinue \u22652 months before planned pregnancy"],
    routes: "Subcutaneous",
    commonVialMg: [2.5, 5, 7.5, 10, 12.5, 15],
    recommendedReconstitutionMl: [1, 2],
    reconstitutionNote: "Commercial single-dose pens come pre-filled — no reconstitution needed. For compounded vials: add bacteriostatic water slowly, swirl gently.",
    storageNote: "Refrigerate at 2–8 °C. Do not freeze. In-use pen may be stored at ≤30 °C for up to 21 days.",
    syringeNote: "Commercial formulation uses auto-injector pens. For compounded vials: standard insulin syringe (U-100).",
    lastReviewed: "2024-12-01",
    regimens: [
      {
        label: "Initiation (2.5 mg × 4 weeks)",
        dosePerInjection_mg: 2.5,
        frequencyPerWeek: 1,
        route: "Subcutaneous",
        timingNote: "Once weekly, consistent day preferred",
        maxDurationDays: 28,
        evidenceTag: "Clinical / FDA-approved",
        warnings: ["GI effects (nausea, diarrhea) most common at initiation and dose increases", "Black Box Warning: thyroid C-cell tumors in rodents; relevance to humans unknown", "Monitor for signs of pancreatitis and gallbladder disease"],
        references: ["https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/217806s000lbl.pdf"],
      },
      {
        label: "Maintenance (5 mg → 10 mg/week)",
        dosePerInjection_mg: 5,
        frequencyPerWeek: 1,
        route: "Subcutaneous",
        timingNote: "Once weekly",
        maxDurationDays: "$undefined",
        evidenceTag: "Clinical / FDA-approved",
        warnings: ["Titrate slowly to minimize GI effects", "Physician supervision required"],
        references: ["https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/217806s000lbl.pdf", "https://pubmed.ncbi.nlm.nih.gov/36516074/"],
        titrationSteps: [{"week": 5, "dosePerInjection_mg": 5, "note": "Increase from 2.5 mg if tolerated"}, {"week": 9, "dosePerInjection_mg": 7.5, "note": "Optional escalation"}, {"week": 13, "dosePerInjection_mg": 10, "note": "Optional escalation"}],
      },
      {
        label: "Maximum dose (15 mg/week)",
        dosePerInjection_mg: 15,
        frequencyPerWeek: 1,
        route: "Subcutaneous",
        timingNote: "Once weekly",
        maxDurationDays: "$undefined",
        evidenceTag: "Clinical / FDA-approved",
        warnings: ["15 mg is the maximum approved weekly dose", "Requires slow titration over \u226520 weeks from initiation", "Higher GI side effect burden", "Requires physician supervision"],
        references: ["https://pubmed.ncbi.nlm.nih.gov/36516074/"],
      },
    ],
  },
]

export type Peptide = (typeof PEPTIDES)[number]
export const PEPTIDE_NAMES: string[] = PEPTIDES.map(p => p.name)
